version: '3.8'
services:
  api-gateway:
    build:
      context: .
      dockerfile: packages/services/api-gateway/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - notes-service

  notes-service:
    build:
      context: .
      dockerfile: packages/services/notes-service/Dockerfile
    ports:
      - "3333:3333"
